/**
 * Mock data for all API endpoints.
 * Provides realistic Nigerian artisan data for UI testing without a backend.
 */

import type { WorkerProfile, WorkerProfileSummary, WorkerSearchResponse } from "./types/worker";
import type {
  Job,
  JobSummary,
  JobApplication,
  JobStage,
  CustomerJobStats,
  WorkerJobStats,
} from "./types/job";
import type {
  WorkerReputation,
  ReviewSummary,
  Review,
  WorkerCreditProfile,
} from "./types/reputation";
import type { VirtualAccount, Transaction } from "@/store/paymentStore";
import type { ServiceCategory } from "@/lib/constants/categories";

// ─── Workers / Marketplace ───────────────────────────────────────────────────

const mockCategories: ServiceCategory[] = [
  {
    id: "home-services",
    name: "Home Services",
    slug: "home-services",
    icon: "home",
    description: "Repairs, installations, and maintenance",
    subcategories: ["Electrician", "Plumber", "Carpenter"],
  },
  {
    id: "personal-services",
    name: "Personal Services",
    slug: "personal-services",
    icon: "scissors",
    description: "Personal care and fashion services",
    subcategories: ["Tailor", "Hairstylist", "Barber"],
  },
  {
    id: "tech-services",
    name: "Tech Services",
    slug: "tech-services",
    icon: "smartphone",
    description: "Technology repair and digital services",
    subcategories: ["Web Developer", "Phone Repair", "Graphic Designer"],
  },
];

export const mockWorkerProfiles: WorkerProfile[] = [
  {
    id: "worker-1",
    user_id: "user-1",
    display_name: "Chinedu Okafor",
    username: "chinedu-okafor",
    bio: "Master electrician with 12 years of experience in residential and commercial wiring. Certified by NABTEB. I take pride in clean, safe installations that pass inspection the first time.",
    phone: "+234 801 234 5678",
    skills: [
      { id: "s1", name: "Electrical Wiring", years_experience: 12, verified: true },
      { id: "s2", name: "Solar Installation", years_experience: 5, verified: true },
      { id: "s3", name: "Generator Repair", years_experience: 8, verified: false },
    ],
    categories: [mockCategories[0]],
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    portfolio: [
      {
        id: "p1",
        title: "Full House Rewiring - Lekki",
        description: "Complete rewiring of a 5-bedroom duplex including new distribution board, circuit breakers, and all socket/light points. Passed PHCN inspection on first attempt.",
        image_url: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&h=300&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=800&h=600&fit=crop",
        ],
        created_at: "2024-08-15T10:00:00Z",
        category: "Electrical",
      },
      {
        id: "p2",
        title: "Solar Panel Installation",
        description: "5kW solar system for a residential property with battery backup. Includes inverter setup, panel mounting, and full wiring to changeover switch.",
        image_url: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=400&h=300&fit=crop",
        images: [
          "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=800&h=600&fit=crop",
          "https://images.unsplash.com/photo-1611365892117-00ac6fb5136d?w=800&h=600&fit=crop",
        ],
        created_at: "2024-07-20T10:00:00Z",
        category: "Solar",
      },
      {
        id: "p8",
        title: "Generator Maintenance & Repair",
        description: "Complete overhaul of a 20kVA Mikano generator including engine servicing, alternator repair, and automatic transfer switch installation for a commercial building.",
        image_url: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&h=300&fit=crop",
        created_at: "2024-09-10T10:00:00Z",
        category: "Generator",
      },
    ],
    trust_score: 92,
    credit_score: { score: 745, last_updated: "2024-11-01T00:00:00Z", factors: { job_completion: 95, earnings_consistency: 80, tenure: 85, verification_level: 90 } },
    verification_status: "verified",
    hourly_rate: 5000,
    minimum_budget: 15000,
    completed_jobs: 87,
    completion_rate: 95,
    rating: 4.8,
    reviews_count: 64,
    availability: "available",
    response_time_hours: 1,
    profile_image_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    experience: [
      { id: "exp-1", title: "Lead Electrician", company: "SolarPro Nigeria Ltd", start_year: 2019, description: "Leading a team of 8 electricians on large-scale solar installation projects for commercial and residential clients. Managed over 200+ successful installations with zero safety incidents." },
      { id: "exp-2", title: "Senior Electrician", company: "Lagos Power Solutions", start_year: 2015, end_year: 2019, description: "Specialized in industrial electrical systems, including factory automation, power distribution, and emergency backup systems." },
      { id: "exp-3", title: "Electrical Technician", company: "ElectriCare Services", start_year: 2012, end_year: 2015, description: "Residential wiring, maintenance, and troubleshooting for homes and small businesses across Lagos." },
    ],
    education: [
      { id: "edu-1", title: "HND in Electrical Engineering", institution: "Yaba College of Technology", year: 2011 },
      { id: "edu-2", title: "Trade Certificate in Electrical Installation", institution: "Lagos Technical School", year: 2008 },
    ],
    certifications: [
      { id: "cert-1", title: "Certified Solar PV Installer", issuer: "Solar Energy Society of Nigeria", year: 2020 },
      { id: "cert-2", title: "Electrical Safety Certification", issuer: "Nigerian Electricity Regulatory Commission", year: 2021 },
    ],
    languages: ["English", "Yoruba", "Pidgin"],
    created_at: "2022-03-10T08:00:00Z",
    updated_at: "2024-11-15T14:30:00Z",
  },
  {
    id: "worker-2",
    user_id: "user-2",
    display_name: "Amina Bello",
    username: "amina-bello",
    bio: "Professional tailor specializing in traditional and modern Nigerian fashion. I create bespoke aso-oke, agbada, and contemporary designs. Quick turnaround for events.",
    phone: "+234 802 345 6789",
    skills: [
      { id: "s4", name: "Tailoring", years_experience: 8, verified: true },
      { id: "s5", name: "Fashion Design", years_experience: 6, verified: true },
      { id: "s6", name: "Embroidery", years_experience: 10, verified: false },
    ],
    categories: [mockCategories[1]],
    location: { city: "Abuja", state: "FCT", country: "Nigeria" },
    portfolio: [
      {
        id: "p3",
        title: "Wedding Aso-Oke Collection",
        description: "Custom bridal aso-oke with modern twist",
        image_url: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=400&h=300&fit=crop",
        created_at: "2024-09-01T10:00:00Z",
        category: "Fashion",
      },
    ],
    trust_score: 88,
    verification_status: "verified",
    hourly_rate: 3500,
    minimum_budget: 10000,
    completed_jobs: 124,
    completion_rate: 97,
    rating: 4.9,
    reviews_count: 98,
    availability: "available",
    response_time_hours: 2,
    profile_image_url: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face",
    created_at: "2021-06-15T08:00:00Z",
    updated_at: "2024-11-10T09:00:00Z",
  },
  {
    id: "worker-3",
    user_id: "user-3",
    display_name: "Emeka Nwosu",
    username: "emeka-nwosu",
    bio: "Experienced plumber handling everything from pipe fitting to full bathroom renovations. Available for emergency calls 24/7 across Lagos mainland and island.",
    skills: [
      { id: "s7", name: "Plumbing", years_experience: 10, verified: true },
      { id: "s8", name: "Pipe Fitting", years_experience: 10, verified: true },
      { id: "s9", name: "Bathroom Renovation", years_experience: 6, verified: false },
    ],
    categories: [mockCategories[0]],
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    portfolio: [
      {
        id: "p10",
        title: "Bathroom Renovation - Victoria Island",
        description: "Complete bathroom overhaul with modern fixtures",
        image_url: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400&h=300&fit=crop",
        created_at: "2024-05-10T10:00:00Z",
        category: "Plumbing",
      },
    ],
    trust_score: 75,
    verification_status: "verified",
    hourly_rate: 4000,
    minimum_budget: 8000,
    completed_jobs: 53,
    completion_rate: 89,
    rating: 4.3,
    reviews_count: 38,
    availability: "busy",
    response_time_hours: 3,
    profile_image_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    created_at: "2022-09-01T08:00:00Z",
    updated_at: "2024-10-28T11:00:00Z",
  },
  {
    id: "worker-4",
    user_id: "user-4",
    display_name: "Fatima Abdullahi",
    username: "fatima-abdullahi",
    bio: "Professional hairstylist specializing in braids, locs, and natural hair care. I bring the salon experience to your doorstep with premium products and techniques.",
    skills: [
      { id: "s10", name: "Hair Styling", years_experience: 7, verified: true },
      { id: "s11", name: "Braiding", years_experience: 9, verified: true },
      { id: "s12", name: "Natural Hair Care", years_experience: 5, verified: true },
    ],
    categories: [mockCategories[1]],
    location: { city: "Abuja", state: "FCT", country: "Nigeria" },
    portfolio: [
      {
        id: "p4",
        title: "Bridal Hair Collection",
        description: "Elegant bridal hairstyles for traditional and white weddings",
        image_url: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=300&fit=crop",
        created_at: "2024-10-05T10:00:00Z",
        category: "Hair",
      },
    ],
    trust_score: 82,
    verification_status: "verified",
    hourly_rate: 4500,
    minimum_budget: 5000,
    completed_jobs: 201,
    completion_rate: 96,
    rating: 4.7,
    reviews_count: 156,
    availability: "available",
    response_time_hours: 1,
    profile_image_url: "https://images.unsplash.com/photo-1589156229687-496a31ad1d1f?w=150&h=150&fit=crop&crop=face",
    created_at: "2021-01-20T08:00:00Z",
    updated_at: "2024-11-12T16:00:00Z",
  },
  {
    id: "worker-5",
    user_id: "user-5",
    display_name: "Oluwaseun Adeyemi",
    username: "oluwaseun-adeyemi",
    bio: "Full-stack web developer and UI/UX designer. I build responsive websites, mobile apps, and e-commerce platforms for Nigerian businesses. React, Next.js, Node.js expert.",
    skills: [
      { id: "s13", name: "Web Development", years_experience: 6, verified: true },
      { id: "s14", name: "UI/UX Design", years_experience: 4, verified: false },
      { id: "s15", name: "Mobile App Development", years_experience: 3, verified: false },
    ],
    categories: [mockCategories[2]],
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    portfolio: [
      {
        id: "p5",
        title: "E-commerce Platform",
        description: "Built a full e-commerce solution for a Lagos fashion brand",
        image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop",
        created_at: "2024-06-15T10:00:00Z",
        category: "Tech",
      },
    ],
    trust_score: 70,
    verification_status: "pending",
    hourly_rate: 8000,
    minimum_budget: 50000,
    completed_jobs: 28,
    completion_rate: 85,
    rating: 4.5,
    reviews_count: 19,
    availability: "available",
    response_time_hours: 2,
    profile_image_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    created_at: "2023-02-01T08:00:00Z",
    updated_at: "2024-11-08T10:00:00Z",
  },
  {
    id: "worker-6",
    user_id: "user-6",
    display_name: "Ibrahim Musa",
    username: "ibrahim-musa",
    bio: "Master carpenter with expertise in custom furniture, kitchen cabinets, and interior woodwork. I use quality hardwood and modern joinery techniques for lasting results.",
    skills: [
      { id: "s16", name: "Carpentry", years_experience: 15, verified: true },
      { id: "s17", name: "Furniture Making", years_experience: 12, verified: true },
      { id: "s18", name: "Wood Finishing", years_experience: 10, verified: true },
    ],
    categories: [mockCategories[0]],
    location: { city: "Kano", state: "Kano", country: "Nigeria" },
    portfolio: [
      {
        id: "p6",
        title: "Custom Kitchen Cabinets",
        description: "Mahogany kitchen cabinets with soft-close hinges",
        image_url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop",
        created_at: "2024-04-10T10:00:00Z",
        category: "Woodwork",
      },
    ],
    trust_score: 95,
    credit_score: { score: 780, last_updated: "2024-11-01T00:00:00Z", factors: { job_completion: 98, earnings_consistency: 90, tenure: 95, verification_level: 95 } },
    verification_status: "verified",
    hourly_rate: 4500,
    minimum_budget: 20000,
    completed_jobs: 156,
    completion_rate: 98,
    rating: 4.9,
    reviews_count: 132,
    availability: "available",
    response_time_hours: 4,
    profile_image_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    created_at: "2020-05-01T08:00:00Z",
    updated_at: "2024-11-14T08:00:00Z",
  },
  {
    id: "worker-7",
    user_id: "user-7",
    display_name: "Ngozi Eze",
    username: "ngozi-eze",
    bio: "Certified makeup artist and beauty consultant. Specializing in bridal makeup, editorial looks, and everyday glam. I use only premium, skin-friendly products.",
    skills: [
      { id: "s19", name: "Makeup Artistry", years_experience: 6, verified: true },
      { id: "s20", name: "Bridal Makeup", years_experience: 5, verified: true },
      { id: "s21", name: "Skincare", years_experience: 3, verified: false },
    ],
    categories: [mockCategories[1]],
    location: { city: "Port Harcourt", state: "Rivers", country: "Nigeria" },
    portfolio: [
      {
        id: "p11",
        title: "Bridal Glam - Traditional Wedding",
        description: "Full bridal makeup with lashes and setting spray",
        image_url: "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=300&fit=crop",
        created_at: "2024-08-22T10:00:00Z",
        category: "Makeup",
      },
    ],
    trust_score: 65,
    verification_status: "verified",
    hourly_rate: 6000,
    minimum_budget: 15000,
    completed_jobs: 42,
    completion_rate: 91,
    rating: 4.6,
    reviews_count: 35,
    availability: "available",
    response_time_hours: 2,
    profile_image_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face",
    created_at: "2022-11-01T08:00:00Z",
    updated_at: "2024-11-05T12:00:00Z",
  },
  {
    id: "worker-8",
    user_id: "user-8",
    display_name: "Tunde Bakare",
    username: "tunde-bakare",
    bio: "Professional photographer and videographer covering weddings, events, and commercial shoots. Drone photography available. Based in Lagos but travel nationwide.",
    skills: [
      { id: "s22", name: "Photography", years_experience: 9, verified: true },
      { id: "s23", name: "Videography", years_experience: 7, verified: true },
      { id: "s24", name: "Drone Photography", years_experience: 3, verified: false },
    ],
    categories: [mockCategories[2]],
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    portfolio: [
      {
        id: "p7",
        title: "Wedding Coverage",
        description: "Full day wedding photography and videography",
        image_url: "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=300&fit=crop",
        created_at: "2024-09-20T10:00:00Z",
        category: "Photography",
      },
    ],
    trust_score: 78,
    verification_status: "verified",
    hourly_rate: 10000,
    minimum_budget: 50000,
    completed_jobs: 67,
    completion_rate: 88,
    rating: 4.4,
    reviews_count: 52,
    availability: "busy",
    response_time_hours: 6,
    profile_image_url: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face",
    created_at: "2021-08-15T08:00:00Z",
    updated_at: "2024-11-01T09:00:00Z",
  },
];

// Taglines for each worker to show personality
const workerTaglines: Record<string, string> = {
  "worker-1": "Specializes in full-house rewiring & solar installations",
  "worker-2": "Expert in bespoke aso-oke & modern Nigerian fashion",
  "worker-3": "Available 24/7 for emergency plumbing across Lagos",
  "worker-4": "Brings the salon experience to your doorstep",
  "worker-5": "Builds responsive websites & e-commerce for Nigerian brands",
  "worker-6": "Master craftsman — custom furniture with premium hardwood",
  "worker-7": "Bridal makeup specialist with premium products",
  "worker-8": "Wedding & event coverage with drone photography",
};

// Featured reviews for social proof on cards
const workerFeaturedReviews: Record<string, { comment: string; reviewer_name: string; rating: number }> = {
  "worker-1": { comment: "Fixed my generator in 30 minutes — lifesaver!", reviewer_name: "Hauwa S.", rating: 5 },
  "worker-2": { comment: "The agbada was perfect. Everyone at the wedding asked for her number.", reviewer_name: "Olumide F.", rating: 5 },
  "worker-3": { comment: "Came at midnight for an emergency. Very reliable.", reviewer_name: "Kemi A.", rating: 4 },
  "worker-4": { comment: "Best braids I've ever had. So gentle and fast!", reviewer_name: "Chioma N.", rating: 5 },
  "worker-5": { comment: "Our restaurant website looks amazing. Orders doubled!", reviewer_name: "Adebayo J.", rating: 4 },
  "worker-6": { comment: "The cabinets are museum quality. Worth every naira.", reviewer_name: "Hauwa S.", rating: 5 },
  "worker-7": { comment: "Made me feel like a queen on my wedding day.", reviewer_name: "Blessing O.", rating: 5 },
  "worker-8": { comment: "Captured moments we didn't even know happened. Incredible eye.", reviewer_name: "Tola M.", rating: 5 },
};

// Response times
const workerResponseTimes: Record<string, string> = {
  "worker-1": "~1 hour",
  "worker-2": "~2 hours",
  "worker-3": "~3 hours",
  "worker-4": "~1 hour",
  "worker-5": "~2 hours",
  "worker-6": "~4 hours",
  "worker-7": "~2 hours",
  "worker-8": "~6 hours",
};

function toWorkerSummary(worker: WorkerProfile): WorkerProfileSummary {
  return {
    id: worker.id,
    user_id: worker.user_id,
    display_name: worker.display_name,
    username: worker.username,
    profile_image_url: worker.profile_image_url,
    skills: worker.skills.map((s) => s.name),
    primary_category: worker.categories[0]?.name || "General",
    location: { city: worker.location.city, state: worker.location.state },
    trust_score: worker.trust_score,
    rating: worker.rating,
    reviews_count: worker.reviews_count,
    completed_jobs: worker.completed_jobs,
    hourly_rate: worker.hourly_rate,
    verification_status: worker.verification_status,
    availability: worker.availability,
    tagline: workerTaglines[worker.id],
    portfolio_preview: worker.portfolio[0]
      ? { image_url: worker.portfolio[0].image_url, title: worker.portfolio[0].title }
      : undefined,
    featured_review: workerFeaturedReviews[worker.id],
    response_time: workerResponseTimes[worker.id],
  };
}

export const mockWorkerSummaries: WorkerProfileSummary[] = mockWorkerProfiles.map(toWorkerSummary);

export const mockWorkerSearchResponse: WorkerSearchResponse = {
  workers: mockWorkerSummaries,
  total: mockWorkerSummaries.length,
  page: 1,
  limit: 20,
  has_more: false,
};

export const mockRecommendations: WorkerProfileSummary[] = mockWorkerSummaries.slice(0, 4);


// ─── Jobs ────────────────────────────────────────────────────────────────────

export const mockJobStages: JobStage[] = [
  {
    id: "stage-1",
    job_id: "job-1",
    title: "Initial Assessment",
    description: "Inspect the electrical system and provide a detailed quote",
    amount: 5000,
    status: "completed",
    completed_at: "2024-11-02T14:00:00Z",
    created_at: "2024-10-28T10:00:00Z",
    order: 1,
  },
  {
    id: "stage-2",
    job_id: "job-1",
    title: "Wiring Installation",
    description: "Install new wiring throughout the ground floor",
    amount: 45000,
    status: "in_progress",
    due_date: "2024-11-20T00:00:00Z",
    created_at: "2024-10-28T10:00:00Z",
    order: 2,
  },
  {
    id: "stage-3",
    job_id: "job-1",
    title: "Testing & Certification",
    description: "Test all circuits and provide safety certification",
    amount: 10000,
    status: "pending",
    due_date: "2024-11-25T00:00:00Z",
    created_at: "2024-10-28T10:00:00Z",
    order: 3,
  },
];

export const mockJobs: Job[] = [
  {
    id: "job-1",
    title: "Electrical Rewiring - 3 Bedroom Flat",
    description: "Need complete electrical rewiring for a 3-bedroom flat in Lekki Phase 1. The current wiring is over 20 years old and needs to be brought up to modern standards.",
    category: mockCategories[0],
    budget_min: 50000,
    budget_max: 80000,
    final_amount: 60000,
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    customer_id: "customer-1",
    customer_name: "Adebayo Johnson",
    worker_id: "worker-1",
    worker: mockWorkerSummaries[0],
    status: "in_progress",
    stages: mockJobStages,
    created_at: "2024-10-28T10:00:00Z",
    updated_at: "2024-11-10T14:00:00Z",
    deadline: "2024-11-30T00:00:00Z",
    started_at: "2024-11-01T09:00:00Z",
    requirements: ["Must use quality copper wiring", "Work during daytime only", "Clean up daily"],
  },
  {
    id: "job-2",
    title: "Custom Agbada for Wedding",
    description: "Need a custom agbada set (agbada, buba, sokoto, and fila) for my brother's wedding. Premium fabric provided. Need embroidery on the agbada.",
    category: mockCategories[1],
    budget_min: 25000,
    budget_max: 45000,
    location: { city: "Abuja", state: "FCT", country: "Nigeria" },
    customer_id: "customer-2",
    customer_name: "Olumide Fashola",
    status: "open",
    stages: [],
    created_at: "2024-11-05T08:00:00Z",
    updated_at: "2024-11-05T08:00:00Z",
    deadline: "2024-12-15T00:00:00Z",
    requirements: ["Experience with aso-oke", "Portfolio of previous agbada work"],
  },
  {
    id: "job-3",
    title: "Website Redesign for Restaurant",
    description: "Our restaurant website needs a complete redesign. We want online ordering, menu management, and reservation system. Must be mobile-friendly.",
    category: mockCategories[2],
    budget_min: 150000,
    budget_max: 300000,
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    customer_id: "customer-1",
    customer_name: "Adebayo Johnson",
    worker_id: "worker-5",
    worker: mockWorkerSummaries[4],
    status: "in_progress",
    stages: [
      {
        id: "stage-4",
        job_id: "job-3",
        title: "Design Mockups",
        description: "Create UI/UX mockups for all pages",
        amount: 80000,
        status: "completed",
        completed_at: "2024-11-08T16:00:00Z",
        created_at: "2024-11-01T10:00:00Z",
        order: 1,
      },
      {
        id: "stage-5",
        job_id: "job-3",
        title: "Frontend Development",
        description: "Build the responsive frontend",
        amount: 120000,
        status: "in_progress",
        due_date: "2024-12-01T00:00:00Z",
        created_at: "2024-11-01T10:00:00Z",
        order: 2,
      },
      {
        id: "stage-6",
        job_id: "job-3",
        title: "Backend & Deployment",
        description: "Set up backend, integrate payments, and deploy",
        amount: 100000,
        status: "pending",
        due_date: "2024-12-15T00:00:00Z",
        created_at: "2024-11-01T10:00:00Z",
        order: 3,
      },
    ],
    created_at: "2024-11-01T10:00:00Z",
    updated_at: "2024-11-10T12:00:00Z",
    deadline: "2024-12-20T00:00:00Z",
    started_at: "2024-11-03T09:00:00Z",
    is_remote: true,
  },
  {
    id: "job-4",
    title: "Kitchen Cabinet Installation",
    description: "Need custom kitchen cabinets for a newly renovated kitchen. Mahogany wood preferred. L-shaped kitchen, approximately 12 feet total.",
    category: mockCategories[0],
    budget_min: 200000,
    budget_max: 350000,
    location: { city: "Kano", state: "Kano", country: "Nigeria" },
    customer_id: "customer-3",
    customer_name: "Hauwa Suleiman",
    worker_id: "worker-6",
    worker: mockWorkerSummaries[5],
    status: "completed",
    stages: [
      {
        id: "stage-7",
        job_id: "job-4",
        title: "Measurement & Design",
        description: "Take measurements and create cabinet design",
        amount: 30000,
        status: "paid",
        completed_at: "2024-09-15T10:00:00Z",
        created_at: "2024-09-10T10:00:00Z",
        order: 1,
      },
      {
        id: "stage-8",
        job_id: "job-4",
        title: "Construction",
        description: "Build the cabinets in workshop",
        amount: 180000,
        status: "paid",
        completed_at: "2024-10-05T16:00:00Z",
        created_at: "2024-09-10T10:00:00Z",
        order: 2,
      },
      {
        id: "stage-9",
        job_id: "job-4",
        title: "Installation & Finishing",
        description: "Install cabinets and apply finishing",
        amount: 90000,
        status: "paid",
        completed_at: "2024-10-12T14:00:00Z",
        created_at: "2024-09-10T10:00:00Z",
        order: 3,
      },
    ],
    created_at: "2024-09-10T10:00:00Z",
    updated_at: "2024-10-12T14:00:00Z",
    started_at: "2024-09-12T09:00:00Z",
    completed_at: "2024-10-12T14:00:00Z",
  },
  {
    id: "job-5",
    title: "Bridal Makeup & Hair",
    description: "Need a makeup artist and hairstylist for my wedding day. Traditional and white wedding looks needed. Bridesmaids (4) also need makeup.",
    category: mockCategories[1],
    budget_min: 80000,
    budget_max: 150000,
    location: { city: "Port Harcourt", state: "Rivers", country: "Nigeria" },
    customer_id: "customer-4",
    customer_name: "Blessing Okonkwo",
    status: "open",
    stages: [],
    created_at: "2024-11-12T09:00:00Z",
    updated_at: "2024-11-12T09:00:00Z",
    deadline: "2025-01-15T00:00:00Z",
    requirements: ["Must have bridal portfolio", "Trial session required", "Available for full day"],
  },
];

export const mockJobSummaries: JobSummary[] = mockJobs.map((job) => ({
  id: job.id,
  title: job.title,
  category: job.category.name,
  budget_min: job.budget_min,
  budget_max: job.budget_max,
  location: { city: job.location.city, state: job.location.state },
  status: job.status,
  customer_name: job.customer_name,
  worker_name: job.worker?.display_name,
  created_at: job.created_at,
  deadline: job.deadline,
  applications_count: job.status === "open" ? Math.floor(Math.random() * 5) + 1 : undefined,
}));

export const mockJobApplications: JobApplication[] = [
  {
    id: "app-1",
    job_id: "job-2",
    worker_id: "worker-2",
    worker: mockWorkerSummaries[1],
    proposed_amount: 35000,
    cover_letter: "I have extensive experience with agbada and aso-oke. I've made over 200 agbada sets for weddings and special occasions. I can deliver within 2 weeks of receiving the fabric.",
    estimated_duration: "2 weeks",
    status: "pending",
    created_at: "2024-11-06T10:00:00Z",
    updated_at: "2024-11-06T10:00:00Z",
  },
  {
    id: "app-2",
    job_id: "job-2",
    worker_id: "worker-4",
    worker: mockWorkerSummaries[3],
    proposed_amount: 40000,
    cover_letter: "While I primarily do hair styling, I also have tailoring skills and have made several agbada sets. I can provide references from previous clients.",
    estimated_duration: "3 weeks",
    status: "pending",
    created_at: "2024-11-07T14:00:00Z",
    updated_at: "2024-11-07T14:00:00Z",
  },
  {
    id: "app-3",
    job_id: "job-5",
    worker_id: "worker-7",
    worker: mockWorkerSummaries[6],
    proposed_amount: 120000,
    cover_letter: "I specialize in bridal makeup and have covered over 50 weddings. My package includes trial session, bride + 4 bridesmaids, touch-up kit, and full-day availability.",
    estimated_duration: "Full day",
    status: "pending",
    created_at: "2024-11-13T08:00:00Z",
    updated_at: "2024-11-13T08:00:00Z",
  },
];

export const mockWorkerJobStats: WorkerJobStats = {
  total_jobs: 87,
  active_jobs: 2,
  completed_jobs: 82,
  total_earned: 4250000,
  pending_earnings: 55000,
  completion_rate: 94.3,
  average_rating: 4.8,
};

export const mockCustomerJobStats: CustomerJobStats = {
  total_jobs: 12,
  active_jobs: 2,
  completed_jobs: 8,
  total_spent: 1850000,
  pending_payments: 165000,
};


// ─── Payments ────────────────────────────────────────────────────────────────

export const mockVirtualAccount: VirtualAccount = {
  account_number: "8012345678",
  bank_name: "Wema Bank",
  account_name: "ARTIVO/Chinedu Okafor",
  status: "active",
  created_at: "2024-06-15T10:00:00Z",
};

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    type: "credit",
    amount: 45000,
    currency: "NGN",
    status: "completed",
    payment_method: "bank_transfer",
    counterparty_name: "Adebayo Johnson",
    job_reference: "job-1",
    created_at: "2024-11-10T14:30:00Z",
    completed_at: "2024-11-10T14:32:00Z",
  },
  {
    id: "txn-2",
    type: "credit",
    amount: 80000,
    currency: "NGN",
    status: "completed",
    payment_method: "mobile_money",
    counterparty_name: "Adebayo Johnson",
    job_reference: "job-3",
    created_at: "2024-11-08T16:00:00Z",
    completed_at: "2024-11-08T16:05:00Z",
  },
  {
    id: "txn-3",
    type: "debit",
    amount: 15000,
    currency: "NGN",
    status: "completed",
    payment_method: "bank_transfer",
    counterparty_name: "Withdrawal to GTBank",
    created_at: "2024-11-07T09:00:00Z",
    completed_at: "2024-11-07T09:15:00Z",
  },
  {
    id: "txn-4",
    type: "credit",
    amount: 30000,
    currency: "NGN",
    status: "completed",
    payment_method: "wallet",
    counterparty_name: "Hauwa Suleiman",
    job_reference: "job-4",
    created_at: "2024-10-12T14:00:00Z",
    completed_at: "2024-10-12T14:01:00Z",
  },
  {
    id: "txn-5",
    type: "credit",
    amount: 180000,
    currency: "NGN",
    status: "completed",
    payment_method: "bank_transfer",
    counterparty_name: "Hauwa Suleiman",
    job_reference: "job-4",
    created_at: "2024-10-05T16:30:00Z",
    completed_at: "2024-10-05T16:35:00Z",
  },
  {
    id: "txn-6",
    type: "credit",
    amount: 90000,
    currency: "NGN",
    status: "pending",
    payment_method: "bank_transfer",
    counterparty_name: "Hauwa Suleiman",
    job_reference: "job-4",
    created_at: "2024-10-12T15:00:00Z",
  },
  {
    id: "txn-7",
    type: "debit",
    amount: 50000,
    currency: "NGN",
    status: "failed",
    payment_method: "mobile_money",
    counterparty_name: "Withdrawal to OPay",
    created_at: "2024-10-01T11:00:00Z",
  },
  {
    id: "txn-8",
    type: "credit",
    amount: 5000,
    currency: "NGN",
    status: "completed",
    payment_method: "wallet",
    counterparty_name: "Adebayo Johnson",
    job_reference: "job-1",
    created_at: "2024-11-02T14:30:00Z",
    completed_at: "2024-11-02T14:31:00Z",
  },
];

// ─── Reputation ──────────────────────────────────────────────────────────────

export const mockReviews: Review[] = [
  {
    id: "review-1",
    job_id: "job-4",
    job_title: "Kitchen Cabinet Installation",
    reviewer_id: "customer-3",
    reviewer_name: "Hauwa Suleiman",
    reviewer_image: "https://placehold.co/50x50/ffd166/333?text=HS",
    reviewee_id: "worker-1",
    rating: 5,
    comment: "Excellent work! The cabinets are beautiful and perfectly fitted. Chinedu was professional, punctual, and kept the workspace clean. Highly recommended.",
    helpful_count: 12,
    created_at: "2024-10-14T10:00:00Z",
    updated_at: "2024-10-14T10:00:00Z",
    is_verified: true,
  },
  {
    id: "review-2",
    job_id: "job-1",
    job_title: "Electrical Rewiring - 3 Bedroom Flat",
    reviewer_id: "customer-1",
    reviewer_name: "Adebayo Johnson",
    reviewer_image: "https://placehold.co/50x50/06d6a0/333?text=AJ",
    reviewee_id: "worker-1",
    rating: 5,
    comment: "Very knowledgeable electrician. Explained everything clearly and the work is top quality. The inspection passed without any issues.",
    helpful_count: 8,
    created_at: "2024-11-05T16:00:00Z",
    updated_at: "2024-11-05T16:00:00Z",
    is_verified: true,
  },
  {
    id: "review-3",
    job_id: "job-3",
    job_title: "Website Redesign for Restaurant",
    reviewer_id: "customer-1",
    reviewer_name: "Adebayo Johnson",
    reviewee_id: "worker-5",
    rating: 4,
    comment: "Good progress so far on the website. The design mockups were impressive. Still waiting for the full delivery but the communication has been great.",
    response: "Thank you for the feedback! I'm working hard on the frontend and will deliver ahead of schedule.",
    response_at: "2024-11-09T10:00:00Z",
    helpful_count: 3,
    created_at: "2024-11-08T18:00:00Z",
    updated_at: "2024-11-09T10:00:00Z",
    is_verified: true,
  },
  {
    id: "review-4",
    job_id: "job-2",
    job_title: "Custom Agbada for Wedding",
    reviewer_id: "customer-2",
    reviewer_name: "Olumide Fashola",
    reviewer_image: "https://placehold.co/50x50/118ab2/fff?text=OF",
    reviewee_id: "worker-2",
    rating: 4,
    comment: "Amina did a great job with the agbada. The embroidery was detailed and the fit was perfect. Delivery was one day late but the quality made up for it.",
    helpful_count: 5,
    created_at: "2024-10-20T12:00:00Z",
    updated_at: "2024-10-20T12:00:00Z",
    is_verified: true,
  },
];

export const mockReviewSummary: ReviewSummary = {
  total_reviews: 64,
  average_rating: 4.8,
  rating_distribution: {
    5: 45,
    4: 14,
    3: 3,
    2: 1,
    1: 1,
  },
  recent_reviews: mockReviews,
};

export const mockReputation: WorkerReputation = {
  trust_score: {
    overall: 78,
    components: {
      completion_rate: 94,
      response_time: 85,
      customer_satisfaction: 92,
      verification_level: 80,
      tenure_months: 32,
    },
    badges: [
      {
        id: "badge-1",
        name: "Verified Pro",
        description: "Identity and skills verified",
        icon: "shield-check",
        earned_at: "2022-06-01T00:00:00Z",
        category: "verification",
      },
      {
        id: "badge-2",
        name: "Top Rated",
        description: "Maintained 4.5+ rating for 6 months",
        icon: "star",
        earned_at: "2023-01-15T00:00:00Z",
        category: "achievement",
      },
      {
        id: "badge-3",
        name: "50 Jobs",
        description: "Completed 50 jobs on the platform",
        icon: "trophy",
        earned_at: "2023-08-20T00:00:00Z",
        category: "milestone",
      },
      {
        id: "badge-4",
        name: "Quick Responder",
        description: "Average response time under 2 hours",
        icon: "zap",
        earned_at: "2024-02-10T00:00:00Z",
        category: "achievement",
      },
    ],
    last_updated: "2024-11-15T00:00:00Z",
    trend: "up",
    trend_change: 3,
  },
  review_summary: mockReviewSummary,
  history: [
    { date: "2024-11-01T00:00:00Z", trust_score: 78 },
    { date: "2024-10-01T00:00:00Z", trust_score: 76, event: "Completed job #82" },
    { date: "2024-09-01T00:00:00Z", trust_score: 75 },
    { date: "2024-08-01T00:00:00Z", trust_score: 74, event: "Earned Top Rated badge" },
    { date: "2024-07-01T00:00:00Z", trust_score: 72 },
    { date: "2024-06-01T00:00:00Z", trust_score: 70, event: "Verification completed" },
  ],
  insights: [
    {
      type: "positive",
      title: "Excellent Completion Rate",
      description: "Your 94% completion rate is above the platform average of 82%",
      impact: 15,
      action: "Keep accepting jobs you can deliver on time",
    },
    {
      type: "positive",
      title: "Fast Response Time",
      description: "You respond to inquiries within 1 hour on average",
      impact: 10,
    },
    {
      type: "neutral",
      title: "Verification Opportunity",
      description: "Complete advanced verification to boost your trust score by up to 10 points",
      impact: 10,
      action: "Go to Settings > Verification to start",
    },
  ],
  rank_percentile: 85,
};

// ─── Credit ──────────────────────────────────────────────────────────────────

export const mockCreditProfile: WorkerCreditProfile = {
  credit_score: {
    score: 680,
    components: {
      job_completion: 88,
      earnings_consistency: 72,
      tenure: 80,
      verification_level: 75,
      payment_history: 85,
    },
    last_updated: "2024-11-15T00:00:00Z",
    trend: "up",
    trend_change: 12,
    eligible_products: [
      {
        id: "prod-1",
        name: "Artisan Micro Loan",
        type: "loan",
        provider: "FairMoney",
        description: "Quick loans up to ₦200,000 for tools and materials",
        min_credit_score: 600,
        max_amount: 200000,
        interest_rate: 3.5,
        terms: "1-6 months repayment",
      },
      {
        id: "prod-2",
        name: "Equipment Finance",
        type: "credit_line",
        provider: "Carbon",
        description: "Finance equipment purchases with flexible repayment",
        min_credit_score: 650,
        max_amount: 500000,
        interest_rate: 4.0,
        terms: "3-12 months",
      },
      {
        id: "prod-3",
        name: "Artisan Savings Plan",
        type: "savings",
        provider: "PiggyVest",
        description: "Automated savings with 10% annual returns",
        min_credit_score: 500,
        terms: "Flexible withdrawal",
      },
      {
        id: "prod-4",
        name: "Work Insurance",
        type: "insurance",
        provider: "Leadway",
        description: "Coverage for work-related injuries and tool damage",
        min_credit_score: 550,
        terms: "Monthly premium from ₦2,000",
      },
    ],
  },
  history: [
    { date: "2024-11-01T00:00:00Z", score: 680 },
    { date: "2024-10-01T00:00:00Z", score: 668, event: "Consistent earnings for 3 months" },
    { date: "2024-09-01T00:00:00Z", score: 655 },
    { date: "2024-08-01T00:00:00Z", score: 640, event: "Completed verification" },
    { date: "2024-07-01T00:00:00Z", score: 620 },
    { date: "2024-06-01T00:00:00Z", score: 600, event: "First 6 months on platform" },
  ],
  insights: [
    {
      type: "positive",
      title: "Strong Payment History",
      description: "All your received payments have been processed successfully",
      impact: "+15 points",
      action: "Continue maintaining clean payment records",
    },
    {
      type: "positive",
      title: "Growing Earnings",
      description: "Your monthly earnings have increased 20% over the last quarter",
      impact: "+12 points",
    },
    {
      type: "neutral",
      title: "Diversify Income Sources",
      description: "Working with more customers can improve your earnings consistency score",
      impact: "+8 points potential",
      action: "Apply to jobs from new customers",
    },
    {
      type: "negative",
      title: "Short Platform Tenure",
      description: "Your tenure score will improve as you spend more time on the platform",
      impact: "-5 points",
      action: "Stay active and complete jobs regularly",
    },
  ],
  financial_summary: {
    total_earnings: 4250000,
    average_monthly_earnings: 354167,
    earnings_trend: "up",
    on_time_payment_rate: 98,
  },
};

// ─── Onboarding ──────────────────────────────────────────────────────────────

export const mockOnboardingProcessResponse = {
  extracted: {
    display_name: "Chinedu Okafor",
    skills: ["Electrical Wiring", "Solar Installation", "Generator Repair"],
    categories: ["Home Services"],
    location: { city: "Lagos", state: "Lagos", country: "Nigeria" },
    bio: "Master electrician with 12 years of experience",
  },
  confidence: 0.92,
};

export const mockOnboardingResumeResponse = null;
